### ISSUE TITLE
Invalid STDF File, Cannot determine endianness

### ISSUE THREAD

**Issue by alexlyapin** [noonchen/rust-stdf#16]
Tried to run example script with several of my STDF files (generated by probers, all valid and checked with other software) and got "Invalid STDF File, Cannot determine endianness" for each of them. Unfortunately can't provide example of files due to IP. What can go wrong and how can I fix this issue?

**Comment by mon04** [comment]
Did you find a solution to your problem? I am having the same issue ~even with the demo STDF file provided in the repo~. Edit: my mistake, the demo STDF works fine. However I do have an issue with my own STDF file.

Using a debugger, we encounter the error when the code tries to determine the endianness based on the `REC_LEN` of the initial FAR record. In this case, the `REC_LEN` is somehow parsed as `19280` instead of either `2` (LE)  or `512` (BE).

![rust-stdf-endianness-error](https://github.com/user-attachments/assets/1bdce373-423f-4054-8708-ca706ff1eb3a)

**Comment by noonchen-ni** [comment]
@mon04 generally it means the file is not a STDF. Considering the FAR is at the beginning of the file, you can open it using hex viewer and do a manual check.

As for the possible reasons, you may provide a compressed STDF but the code fails to determine the correct compress type based on the file extension, or the default decompress algorithm is not for your file.

**Comment by mon04** [comment]
@noonchen-ni thank you for your response. On closer inspection, I was using a corrupted/invalid STDF file which is what was causing the issue. Also, note my edit to my previous comment. The demo STDF files do not encounter this error. That was a mistake.
